spring.application.name=ParsalManagement
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://database-1.cgfkck8aa8ru.us-east-1.rds.amazonaws.com:3306/sprint
spring.datasource.username=admin
spring.datasource.password=9381094638
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
